### ISSUE TITLE
Session is undefined

### ISSUE THREAD

**Issue by ghost** [wcamarao/session.socket.io#32]
```
sessionSockets.on('connection', function (err, socket, session) {
  console.log(socket); 
  console.log(session); // undefined
});
```

I'm having trouble figuring out why my session is undefined. Any ideas on why this would happen?

Here is my console output https://gist.github.com/gh-naylor/1b45b2a1cfb9fcd515a6

I'm using https://github.com/wcamarao/session.socket.io/issues/20#issuecomment-17664375 from @tanema as a guide.

**Comment by haremo** [comment]
what was the error? i am facing the same ...

**Comment by sovanna** [comment]
me too, same error, what did you do ?
