### ISSUE TITLE
Problems with example code in README.md

### ISSUE THREAD

**Issue by perjg** [wcamarao/session.socket.io#36]
When I copy the example code from README.md, session is always undefined in sessionSockets.on('connection'
err is 'Error: could not look up session by key: connect.sid'

This is the same problem as in issue #2:
https://github.com/wcamarao/session.socket.io/issues/2

This line is what is causing issues:

 app.use(express.session({ store: sessionStore }));

I need to change it to:

app.use(express.session({ secret: 'your secret sauce', store: sessionStore }));

To match the secret given to the cookie parser:

 var cookieParser = express.cookieParser('your secret sauce')
  , sessionStore = new connect.middleware.session.MemoryStore();

This solves the issue. If this is a general problem, perhaps the instructions in README.md ought to be updated?

**Comment by wcamarao** [comment]
Thanks for letting me know, I've updated the docs.
