### ISSUE TITLE
session.socket.io doesn't work

### ISSUE THREAD

**Issue by chechenev** [wcamarao/session.socket.io#38]
I using express 4 + passport with sessions.

I want to make private messages between users with socket.io

Before sending a message from the first user to a second user - I want to verify that the message is really from the first user. To exclude id spoofing in javascript files.

I try to using session.socket.io but it does not work and I can not understand why.

"console.log('connect!');" doesn't work. It seems that the function "sessionSockets.on('connection')"is not executed

Code:

require('./db');

var flash = require('connect-flash');
var mongoose = require('mongoose');
require('./config/passport');

var express = require('express');
var http = require('http');
var path = require('path');
var favicon = require('serve-favicon');
var logger = require('morgan');
var cookieParser = require('cookie-parser');
var bodyParser = require('body-parser');
var passport = require('passport');

var routes = require('./routes');
var users = require('./routes/user');

var session    = require('express-session');
var MongoStore = require('connect-mongo')(session);

var sessionStore = new MongoStore({db:mongoose.connection.db});

var app = express();

app.use(cookieParser('keyboard cat'));
app.use(favicon(__dirname + '/public/favicon.ico'));
app.use(logger('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded());
app.use(express.static(path.join(__dirname, 'public')));

app.use(session({
    secret: 'keyboard cat',
    cookie: {httpOnly: true, secure: true, maxAge: new Date(Date.now() + 3600000)},
    store: sessionStore
}));
app.use(flash());

app.use(passport.initialize());
app.use(passport.session());
app.set('port', process.env.PORT || 3000);

var server = app.listen(app.get('port'), function() {
   // debug('Express server listening on port ' + server.address().port);
});

var io = require('socket.io').listen(server);
var SessionSockets = require('session.socket.io-express4');
var sessionSockets = new SessionSockets(io, sessionStore, cookieParser);

sessionSockets.on('connection', function (err, socket, session) {
  console.log('connect!');

  socket.on('sendMessageToUser', function(data){
    console.log(data);
    console.log('User is ' + req);
 });
//now you can read session.foo from your express routes or connect middlewares
});

**Comment by GeReV** [comment]
I managed to work around similar issues I had with Express 4 and `express-session` package.
My code was something along these lines:

```js
var app = express();
var io = require('socket.io');

var session = require('express-session')({
  name: 'cookiename',
  secret: 'secret',
  resave: false,
  saveUninitialized: true
});

app.use(session);

var server = http.Server(app);

var socket = io(server);

socket.on('connection', function (client) {
  session(client.handshake, {}, function() {
    // The above call embedded sessionID and session.into client.handshake. Its callback doesn't pass anything.
    client.handshake.session.test = 'test';
    client.handshake.session.save();
  });
});
```

Hope this helps anyone.

**Comment by sovanna** [comment]
as @chechenev said, I put the brackets to cookieParser and it works :)

**Comment by wcamarao** [comment]
Thanks @eiriklv for supporting express 4 in the meantime.

I've added support for express 4 just now. It's also published on npm.

**Comment by eiriklv** [comment]
Great stuff @wcamarao! No problem :-)
