### ISSUE TITLE
Compatibility with socket.io 1.0.6 ?

### ISSUE THREAD

**Issue by tomahim** [wcamarao/session.socket.io#40]
Hello,

Since socket.io released a 1.0.6 version, do session.socket.io is compatible with this new version ? I need to migrate to this version and my previous code which contain 
`socket.handshake.getSession` method is saying me that `socket.handshake` has no `getSession` method. 

Is there a workaround or maybe the compatibility with socket.io 1.0.6 is plan soon ?

Thank you

**Comment by wcamarao** [comment]
I've added support for express 4 which was tested with socket.io 1.3.5. It's now published on npm.

Please reopen if you still have any issues.
