### ISSUE TITLE
Session resets when navigating pages

### ISSUE THREAD

**Issue by ganna-shmatova** [wcamarao/session.socket.io#41]
I posted my problem here but did not get much help: http://stackoverflow.com/questions/24417469/express-session-is-undefined-when-accessing-external-website

I'm not quite sure what I did wrong?

Any help would be appreciated.

**Comment by wcamarao** [comment]
You may want to use a production-ready session store. Read more here: https://github.com/expressjs/session

    The default server-side session storage, MemoryStore, is purposely not designed for a production environment. It will leak memory under most conditions, does not scale past a single process, and it meant for debugging and developing.
