### ISSUE TITLE
your example fails in IE

### ISSUE THREAD

**Issue by faeb187** [wcamarao/session.socket.io#42]
<b><i>THX</i></b> for this great package (I have to say this first)
<h4>Issue</h4>
I got this handshake error when using IE (we only support >9, fails in all of them):
<b><i>ERR</i></b> Could not look up session by key: connect.sid

<h4>Sandbox Testing</h4>
So, we decided to run your example script, and oopz... it also fails in IE....
<b><i>URL</i></b> http://217.115.134.41:3187/

![issue](https://cloud.githubusercontent.com/assets/389333/4346678/f8e4e874-410c-11e4-8525-2fcb651fab19.png)

<b><i>NOTE</i></b> This is very urgent, I hope you can provide a solution for this, our projects need to run in this cruel browser too...

<b><i>UPDATE</i></b> In some IE's it seems to work... Now we've got to find out why... 32bit vs 64bit??

**Comment by wcamarao** [comment]
Sorry, not sure how to help you here. Perhaps try stackoverflow.
