### ISSUE TITLE
Better solution

### ISSUE THREAD

**Issue by zevero** [wcamarao/session.socket.io#49]
Respect to wcamarao for developing this tool, which closes an important gap.
Unfortunately it didn't work for me as I could not get around this:

    node_modules/session.socket.io/session.socket.io.js:23
    sessionLookupMethod.call(sessionStore, findCookie(socket.handshake), fun
                          ^
    TypeError: Cannot call method 'call' of undefined

I lost an hour or two googling for similar problems ... until I found:
http://stackoverflow.com/a/29448630/1385546
which links to
https://github.com/xpepermint/socket.io-express-session

Please forgive my boldness, but I can't help that this approach using the new io middleware is far easier and cleaner. (Despite my not fully understanding :)

**Comment by wcamarao** [comment]
That's fantastic, I'll update the README.

The key point is here: http://socket.io/docs/migrating-from-0-9/

> Migration from 0.9
> Socket.io uses middleware now

In other words, if you're using socket.io >= 1.0,
go with https://github.com/xpepermint/socket.io-express-session

Otherwise, https://github.com/wcamarao/session.socket.io

**Comment by zevero** [comment]
Thank you. I am glad that you are so positive about this.

I am sure that many people like me can save time and will have a nicer experience working with express sessions and socket.io!
